[build]
  publish = "frontend/build"
  command = "cd frontend && CI=false npm run build"
  base = "."

[build.environment]
  REACT_APP_API_URL = "https://ttsai-461209.de.r.appspot.com"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://ttsai-461209.de.r.appspot.com"
  NODE_VERSION = "18"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://ttsai-461209.de.r.appspot.com"
  NODE_VERSION = "18"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://ttsai-461209.de.r.appspot.com"
  NODE_VERSION = "18" 