runtime: python39

env_variables:
  SECRET_KEY: "parking-app-secret-key-production-2024"
  JWT_SECRET_KEY: "parking-app-jwt-secret-production-2024"
  MONGODB_URI: "mongodb+srv://adityar42069:3gWpp7BOWrXR9MKf@vehicleparkingapps.wgpt32k.mongodb.net/vehicleparkingapp"
  FLASK_ENV: "production"
  
  # Redis Configuration (DISABLED)
  # REDIS_URL: "redis://:a4JhT7HkNCVDCiwDo4nL212zzSbPSgJR@redis-13431.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:13431/0"
      CACHE_TYPE: simple  # Use simple cache instead of Redis
    # CACHE_REDIS_URL: "redis://:a4JhT7HkNCVDCiwDo4nL212zzSbPSgJR@redis-13431.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:13431/0"  # Redis disabled
        # CELERY_BROKER_URL: "redis://:a4JhT7HkNCVDCiwDo4nL212zzSbPSgJR@redis-13431.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:13431/0"  # Redis disabled
    # CELERY_RESULT_BACKEND: "redis://:a4JhT7HkNCVDCiwDo4nL212zzSbPSgJR@redis-13431.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:13431/0"  # Redis disabled
  
  # Email configuration (optional)
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USE_TLS: "true"
  MAIL_USERNAME: "your-email@gmail.com"
  MAIL_PASSWORD: "your-app-password"
  
  # CORS origins for production - Frontend deployed on Netlify
  CORS_ORIGINS: "https://vehicle-parking-app.netlify.app,http://localhost:3000"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 